# What is PyTorch?

[Link to the tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

## Tensor Creation

The following methods create tensors, which are the foundation of pytorch. Tensors are similar to NumPy's `ndarray`, but can be parallelized across GPUs.

In [2]:
import torch

In [3]:
x = torch.empty(5, 3)  # an unintialized 5x3 matrix
print(x)

tensor([[ 0.0000e+00,  1.5846e+29,  6.6525e+07],
        [ 2.8586e-42,  4.7664e+33,  1.2986e-11],
        [ 2.8953e+32,  7.2251e+28,  4.6999e-39],
        [ 0.0000e+00, -2.1185e+06,  4.5744e-41],
        [ 0.0000e+00,  1.5846e+29,  6.6339e+07]])


In [4]:
x = torch.rand(5, 3)  # a randomly initialized 5x3 matrix
print(x)

tensor([[0.0847, 0.3698, 0.3196],
        [0.0414, 0.1156, 0.1638],
        [0.3442, 0.5939, 0.2625],
        [0.9518, 0.8738, 0.6929],
        [0.2680, 0.6727, 0.7645]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)  # a 5x3 matrix of zeros of a given type
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 2])  # create a tensor from data
print(x)

tensor([5.5000, 2.0000])


In [7]:
print(x.size())  # get tensor size

torch.Size([2])


In [8]:
x = x.new_ones(5, 3)  # create a new tensor based on an existing tensor, will maintain certain properties such as dtype
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## Basic Operations

A full list of operations can be found [here](https://pytorch.org/docs/stable/torch.html)

In [9]:
x = torch.ones(2, 2)
y = torch.ones(2, 2)
z = x + y  # or...
z = torch.add(x, y)
print(z)

tensor([[2., 2.],
        [2., 2.]])


In [11]:
y.add_(x)  # postfix operation with "_" to perform inplace
print(y)

tensor([[2., 2.],
        [2., 2.]])


In [23]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(x[:, 1])  # NumPy-like indexing (all rows, second column)

tensor([ 2,  6, 10])


In [25]:
y = x.view(12)  # use .view to resize
z = x.view(-1, 2)  # -1 means infer from other dimensions
print(y)
print(z)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])


In [26]:
x = torch.tensor([0.5])
print(x.item())  # use .item to get the value from a 1 item tensor

0.5


In [28]:
x = torch.ones(5, 5)
y = x.numpy()  # convert to NumPy array
x.add_(1)  # manipulating the orginal tensor will also affect the NumPy array, and vice-versa
print(x)
print(y)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [29]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)  # convert a numpy to a tensor
np.add(a, 1, out=a)
b.add_(1)
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
